---
driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  env: [CHEF_LICENSE=accept]

transport:
  name: dokken

provisioner:
  name: dokken
  product_name: chef
  product_version: <%= ENV['CHEF_VERSION'] || 'latest' %>
  install_strategy: once

platforms:
  - name: debian-8
    driver:
      image: dokken/debian-8
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools -y

  - name: debian-9
    driver:
      image: dokken/debian-9
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools -y

  - name: centos-6
    driver:
      image: dokken/centos-6
      platform: rhel
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN yum -y install which initscripts net-tools wget

  - name: centos-7
    driver:
      image: dokken/centos-7
      platform: rhel
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN yum -y install lsof which systemd-sysv initscripts wget net-tools

  - name: fedora-28
    driver:
      image: dokken/fedora-28
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN dnf -y install yum which systemd-sysv initscripts wget net-tools

  - name: ubuntu-16.04
    driver:
      image: dokken/ubuntu-16.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools logrotate -y

  - name: ubuntu-18.04
    driver:
      image: dokken/ubuntu-18.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools logrotate -y
